
// Set Micro CRD to match ESP32

#ifndef _MICROCDR_CONFIG_H_
#define _MICROCDR_CONFIG_H_

// Version defines
//#define MICROCDR_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
//#define MICROCDR_VERSION_MINOR @PROJECT_VERSION_MINOR@
//#define MICROCDR_VERSION_MICRO @PROJECT_VERSION_PATCH@
//#define MICROCDR_VERSION_STR "@PROJECT_VERSION@"

// ucdrEndianness defines
#define UCDR_MACHINE_ENDIANNESS UCDR_LITTLE_ENDIANNESS

#endif // _MICROCDR_CONFIG_H_
