---
name: Build and publish Docker Image

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'zenoh_host/**'
      - '.github/workflows/build_and_publish_docker.yaml'

jobs:
  build_images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: zenoh_host
          push: false
          file: zenoh_host/docker/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/roscon2025_control_workshop
